// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: pb/group/group.proto

package group

import (
	context "context"
	user "github.com/harrytflv/protogo/pb/user"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GroupManagementClient is the client API for GroupManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupManagementClient interface {
	Create(ctx context.Context, in *Group, opts ...grpc.CallOption) (*user.Response, error)
}

type groupManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupManagementClient(cc grpc.ClientConnInterface) GroupManagementClient {
	return &groupManagementClient{cc}
}

func (c *groupManagementClient) Create(ctx context.Context, in *Group, opts ...grpc.CallOption) (*user.Response, error) {
	out := new(user.Response)
	err := c.cc.Invoke(ctx, "/protogo.user.GroupManagement/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupManagementServer is the server API for GroupManagement service.
// All implementations must embed UnimplementedGroupManagementServer
// for forward compatibility
type GroupManagementServer interface {
	Create(context.Context, *Group) (*user.Response, error)
	mustEmbedUnimplementedGroupManagementServer()
}

// UnimplementedGroupManagementServer must be embedded to have forward compatible implementations.
type UnimplementedGroupManagementServer struct {
}

func (UnimplementedGroupManagementServer) Create(context.Context, *Group) (*user.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGroupManagementServer) mustEmbedUnimplementedGroupManagementServer() {}

// UnsafeGroupManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupManagementServer will
// result in compilation errors.
type UnsafeGroupManagementServer interface {
	mustEmbedUnimplementedGroupManagementServer()
}

func RegisterGroupManagementServer(s grpc.ServiceRegistrar, srv GroupManagementServer) {
	s.RegisterService(&GroupManagement_ServiceDesc, srv)
}

func _GroupManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protogo.user.GroupManagement/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).Create(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupManagement_ServiceDesc is the grpc.ServiceDesc for GroupManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protogo.user.GroupManagement",
	HandlerType: (*GroupManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GroupManagement_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/group/group.proto",
}
